---
language: objective-c

before_script:
  - sudo easy_install cpp-coveralls

script:
  - xctool -workspace Collator.xcworkspace -scheme 'CollatorTests' build test

after_success:
  - ./Scripts/coveralls.rb --extension m --exclude-folder Test --exclude-folder Externals

